// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bjgkvtlyhfalkpnxmqmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZ2t2dGx5aGZhbGtwbnhtcW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjQ1MDIsImV4cCI6MjA3MDgwMDUwMn0.MIgS2lgjHprI6Ob2UQLr_aXn-XGFzfJ4MAApSvwtrwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);